/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/hotUpdate/index" |
       "/pages/mine/index" |
       "/pages/order/index" |
       "/login-sub/test" |
       "/login-sub/login/index" |
       "/other-sub/topic/index" |
       "/setting-sub/setting/index" |
       "/setting-sub/userInfo/index" |
       "/setting-sub/address/list/edit" |
       "/setting-sub/address/list/index" |
       "/setting-sub/address/manage/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/mine/index" | "/pages/mine/index" | "/pages/mine/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
