/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/attachments/index" |
       "/pages/hotUpdate/index" |
       "/pages/message/index" |
       "/pages/mine/index" |
       "/login-sub/inputCode" |
       "/login-sub/login/index" |
       "/other-sub/topic/index" |
       "/setting-sub/account/changePassword" |
       "/setting-sub/account/index" |
       "/setting-sub/account/realNameAuthentication" |
       "/setting-sub/setting/index" |
       "/setting-sub/setting/recommend" |
       "/setting-sub/setting/userInfo" |
       "/setting-sub/address/list/edit" |
       "/setting-sub/address/list/index" |
       "/setting-sub/address/manage/index" |
       "/product-sub/addSales/index" |
       "/product-sub/attention/index" |
       "/product-sub/historyView/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/attachments/index" | "/pages/message/index" | "/pages/mine/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
